ndvi0:
  name_fmt: FS_1950_NDVI_med_{}.tiff
  dt_fmt: doy
  dir_loc: /vsis/dev-et-data/in/DelawareRiverBasin/NDVI_FORE_SCE_MED/delaware_basin_FS_1950
  climatology: True
ndvi1:
  name_fmt: FS_1960_NDVI_med_{}.tiff
  dt_fmt: doy
  dir_loc: /vsis/dev-et-data/in/DelawareRiverBasin/NDVI_FORE_SCE_MED/delaware_basin_FS_1960
  climatology: True
ndvi2:
  name_fmt: FS_1970_NDVI_med_{}.tiff
  dt_fmt: doy
  dir_loc: /vsis/dev-et-data/in/DelawareRiverBasin/NDVI_FORE_SCE_MED/delaware_basin_FS_1970
  climatology: True
ndvi3:
  name_fmt: FS_1980_NDVI_med_{}.tiff
  dt_fmt: doy
  dir_loc: /vsis/dev-et-data/in/DelawareRiverBasin/NDVI_FORE_SCE_MED/delaware_basin_FS_1980
  climatology: True
ndvi4:
  name_fmt: FS_1990_NDVI_med_{}.tiff
  dt_fmt: doy
  dir_loc: /vsis/dev-et-data/in/DelawareRiverBasin/NDVI_FORE_SCE_MED/delaware_basin_FS_1990
  climatology: True
ndvi5:
  name_fmt: med{}.250_m_NDVI.tif
  dt_fmt: doy
  dir_loc: /vsis3/dev-et-data/in/USA_data/NDVI_med2003_2017/
  climatology: True
ndvi6:
  name_fmt: FS_2010_NDVI_med_{}.tiff
  dt_fmt: doy
  dir_loc: /vsis/dev-et-data/in/DelawareRiverBasin/NDVI_FORE_SCE_MED/delaware_basin_FS_2020
  climatology: True
ndvi7:
  name_fmt: FS_2020_NDVI_med_{}.tiff
  dt_fmt: doy
  dir_loc: /vsis/dev-et-data/in/DelawareRiverBasin/NDVI_FORE_SCE_MED/delaware_basin_FS_2030
  climatology: True
ndvi8:
  name_fmt: FS_2030_NDVI_med_{}.tiff
  dt_fmt: doy
  dir_loc: /vsis/dev-et-data/in/DelawareRiverBasin/NDVI_FORE_SCE_MED/delaware_basin_FS_2040
  climatology: True
ndvi9:
  name_fmt: FS_2040_NDVI_med_{}.tiff
  dt_fmt: doy
  dir_loc: /vsis/dev-et-data/in/DelawareRiverBasin/NDVI_FORE_SCE_MED/delaware_basin_FS_2050
  climatology: True
ndvi10:
  name_fmt: FS_2050_NDVI_med_{}.tiff
  dt_fmt: doy
  dir_loc: /vsis/dev-et-data/in/DelawareRiverBasin/NDVI_FORE_SCE_MED/delaware_basin_FS_2060
  climatology: True
ndvi11:
  name_fmt: FS_2060_NDVI_med_{}.tiff
  dt_fmt: doy
  dir_loc: /vsis/dev-et-data/in/DelawareRiverBasin/NDVI_FORE_SCE_MED/delaware_basin_FS_2070
  climatology: True
ndvi12:
  name_fmt: FS_2070_NDVI_med_{}.tiff
  dt_fmt: doy
  dir_loc: /vsis/dev-et-data/in/DelawareRiverBasin/NDVI_FORE_SCE_MED/delaware_basin_FS_2080
  climatology: True
ndvi13:
  name_fmt: FS_2080_NDVI_med_{}.tiff
  dt_fmt: doy
  dir_loc: /vsis/dev-et-data/in/DelawareRiverBasin/NDVI_FORE_SCE_MED/delaware_basin_FS_2090
  climatology: True

 
 eto0:
  name_fmt: ETo_DOY{}.tif
  dt_fmt: doy
  dir_loc: /vsis/dev-et-data/in/DelawareRiverBasin/ETo_Moving_Average_byDOY/1950_1960/
  climatology: True
eto1:
  name_fmt: ETo_DOY{}.tif
  dt_fmt: doy
  dir_loc: /vsis/dev-et-data/in/DelawareRiverBasin/ETo_Moving_Average_byDOY/1960_1970
  climatology: True
eto2:
  name_fmt: ETo_DOY{}.tif
  dt_fmt: doy
  dir_loc: /vsis/dev-et-data/in/DelawareRiverBasin/ETo_Moving_Average_byDOY/1970_1980
  climatology: True
eto3:
  name_fmt: ETo_DOY{}.tif
  dt_fmt: doy
  dir_loc: /vsis/dev-et-data/in/DelawareRiverBasin/ETo_Moving_Average_byDOY/1980_1990
  climatology: True
eto4:
  name_fmt: ETo_DOY{}.tif
  dt_fmt: doy
  dir_loc: /vsis/dev-et-data/in/DelawareRiverBasin/ETo_Moving_Average_byDOY/1990_2000
  climatology: True
eto5:
  name_fmt: pet{}.tif
  dt_fmt: doy
  dir_loc: /vsis/dev-et-data/in/north_america_data/ETo_mosaic/
  climatology: True
eto6:
  name_fmt: ETo_DOY{}.tif
  dt_fmt: doy
  dir_loc: /vsis/dev-et-data/in/DelawareRiverBasin/ETo_Moving_Average_byDOY/2020_2030
  climatology: True
eto7:
  name_fmt: ETo_DOY{}.tif
  dt_fmt: doy
  dir_loc: /vsis/dev-et-data/in/DelawareRiverBasin/ETo_Moving_Average_byDOY/2030_2040
  climatology: True
eto8:
  name_fmt: ETo_DOY{}.tif
  dt_fmt: doy
  dir_loc: /vsis/dev-et-data/in/DelawareRiverBasin/ETo_Moving_Average_byDOY/2040_2050
  climatology: True
eto9:
  name_fmt: ETo_DOY{}.tif
  dt_fmt: doy
  dir_loc: /vsis/dev-et-data/in/DelawareRiverBasin/ETo_Moving_Average_byDOY/2050_2060
  climatology: True
eto10:
  name_fmt: ETo_DOY{}.tif
  dt_fmt: doy
  dir_loc: /vsis/dev-et-data/in/DelawareRiverBasin/ETo_Moving_Average_byDOY/2060_2070
  climatology: True
eto11:
  name_fmt: ETo_DOY{}.tif
  dt_fmt: doy
  dir_loc: /vsis/dev-et-data/in/DelawareRiverBasin/ETo_Moving_Average_byDOY/2070_2080
  climatology: True
eto12:
  name_fmt: ETo_DOY{}.tif
  dt_fmt: doy
  dir_loc: /vsis/dev-et-data/in/DelawareRiverBasin/ETo_Moving_Average_byDOY/2080_2090
  climatology: True
eto13:
  name_fmt: ETo_DOY{}.tif
  dt_fmt: doy
  dir_loc: /vsis/dev-et-data/in/DelawareRiverBasin/ETo_Moving_Average_byDOY/2090_2100
  climatology: True
  